name: "Run Type Check + Test Files (PR to Main)"

on:
  pull_request:
    branches:
      - main

jobs:
  type_check_and_test:
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine3.21
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - run: npm run typecheck
      - name: Run all test files
        run: npm test
